### ISSUE TITLE
Configure Rust repositories to run ``` cargo +nightly fmt ``` automatically when saving a file.

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/pallet-manta-asset#2]
* Applying formatting automatically when saving should save us some time in reviews.
* Integrate in pallet-manta-asset first.
* Then all other repositories.

**Comment by zhenfeizhang** [comment]
I think it is an IDE feature, rather than configuration.
I used to use Atom with rust plugin, and it does auto fmt.
Now I switched to VS code, with a different plugin, and this is off.
(i am sure there are VS code plugins that enables this feature for you)

**Comment by ghzlatarev** [comment]
Yeah in VSCode settings there is a ```Format on Save``` option
